server.name: kibana
server.host: 0.0.0.0
server.publicBaseUri: "http://localhost:5601"
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.hosts: [ "http://localhost:9200" ]
elasticsearch.username: elastic
elasticsearch.password: test